# Generated by Django 5.0.6 on 2024-05-16 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("plataforma", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AD", "Analise de dados"),
                            ("CD", "Ciencia de dados"),
                            ("AM", "Aprendizado de Maquina"),
                            ("D", "Desenvolvimento"),
                            ("DP", "Desenvolvimento Pessoal"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data", models.DateTimeField(default=datetime.datetime.now)),
                ("tecnologias", models.CharField(default="", max_length=100)),
                ("imagem", models.ImageField(blank=True, upload_to="imagem/%Y/%m/%d/")),
                (
                    "imagem_capa",
                    models.ImageField(blank=True, upload_to="imagem/capa/%Y/%m/%d/"),
                ),
                ("concluido", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateTimeField(default=datetime.datetime.now)),
                ("data_fim", models.DateTimeField()),
                ("tecnologias", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AD", "Analise de dados"),
                            ("CD", "Ciencia de dados"),
                            ("AM", "Aprendizado de Maquina"),
                            ("D", "Desenvolvimento"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data", models.DateTimeField(default=datetime.datetime.now)),
                ("tecnologias", models.CharField(default="", max_length=100)),
                ("imagem", models.ImageField(blank=True, upload_to="imagem/%Y/%m/%d/")),
                (
                    "imagem_capa",
                    models.ImageField(blank=True, upload_to="imagem/capa/%Y/%m/%d/"),
                ),
            ],
        ),
    ]
